ci:
    autofix_commit_msg: |
        chore(pre-commit): auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci

    autoupdate_commit_msg: |
        chore(pre-commit): pre-commit autoupdate

        for more information, see https://pre-commit.ci

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black

default_language_version:
  python: python3.9
